// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urvggpftwjdulhjzevmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVydmdncGZ0d2pkdWxoanpldm1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0ODA0OTcsImV4cCI6MjA2MTA1NjQ5N30.kMYu88tmC4XQDvqyos04KHPQ7q81ld2yx_WmNJBBYCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});